IraSoro/peri

src/modals/InfoModal.css
src/modals/InfoModal.tsx
src/pages/TabHome.css
src/pages/TabHome.tsx

Closed #45 
In this PR styles for `Mark` button from `TabHome.tsx` and `OK` button from `InfoModal` was changed
Also I removed solid border around these buttons because previously there was border duplication, as examples:

Changed style of `Mark` from `TabHome` and `OK` from `InfoModal` buttons

---

src/state/CycleInformationHooks.tsx

Closed #57 
When the current date is set, the time is set with a time zone offset. Therefore, there is a possibility that the current date will be greater than the start date. There was also a bad idea for such a conversion: 
```const diff = new Date(currentDate.getTime() - start.getTime());```
So now I count the difference in days. And I'm adding 1 because the loop includes the current date.
```const diff = currentDate.getDay() - start.getDay() + 1;```

Error when marking a new cycle

---

src/modals/MarkModal.css
src/modals/MarkModal.tsx
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts
src/theme/variables.css
src/translations/ru.tsx

Closed #94
I changed the ui. Now it looks like this
I also moved all calculations to the ```CalculationLogics.ts```.  
I created ```getPastFuturePeriodDays``` function.  In the ```Mark Modal```, in the ```value``` property, I need to transfer all the past period days and the marked current ones. I already have a function for calculating past days - ```getLastPeriodDays```. But for the ```Mark Modal```, I also need to pass the estimated values of the marked periods. That's why I created the ```getPastFuturePeriodDays``` function. In it, I first call a ```getLastPeriodDays``` function to pass the days of the past period, and then I count the current ones.
Now I also updated storage using ```getNewCyclesHistory```. It is past function.
I created a new function to set active dates …

Edit Mark Modal UI

---

src/data/AppVersion.ts
src/modals/Menu.tsx

Closed #103 
I tried the following instruction to set env variables from `.env` file https://create-react-app.dev/docs/adding-custom-environment-variables/ and this works for web version, but doesn't for native android version
I read here https://github.com/ionic-team/ionic-cli/issues/4333 that this issue should be fixed with `.env.production` file or with `REACT_APP_APP_VERSION` env variable set before `ionic cap build android`, but it doesn't work
So, I decided to add file where we can set string with current version number. This solution works fine in both native and web versions
Now you should update `package.json` version and set the same version in `AppVersion.ts` file
Examples of app version displayed in menu:

Add peri version displayed in menu

---

README.md
src/App.tsx
src/data/AppVersion.ts
src/modals/Menu.tsx
src/tests/AppVersion.test.ts
src/translations/ru.tsx

In this PR I added the new functionality to update the current app version to the new one. This auto-update works only on the native version of the app (Android), not on the web version
When you start the application, the menu button will have orange badge which shows that new version is available
On menu button click you'll see button which lets you update your current version
That will open native browser and starts downloading
And prompt you to install

Implement auto-update

---

BUILDING.md
CONTRIBUTING.md
README.md

Closed #144 
I added a `CONTRIBUTING.md` file in which I described the steps for translation into new languages.
I added the `BUILDING.md` file. I moved the build information from the `README.md` file into it.
And edited the `README.md` file.

Added `CONTRIBUTING.md` and `BUILDING.md` files

---

src/pages/TabDetails.tsx

Closed #131 
I fixed the display of the progress bar. Now, if the average cycle length is more than 30, then the progress bar length will be less. Also, for a more beautiful display, I added a progress bar of maximum length 0.95 (for example, for the case where there will be a long delay).
Example for average cycle length less than 30:
Example for average cycle length more than 30:
I fixed the display of the progress bar of the current cycle: now the length of period is `cycles[0].periodLength`, before it was the average value of the period.

Fix progress bar display

---

src/pages/TabHome.tsx
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts
src/utils/translations/ru.ts

Closed #155 
The bug is described in the issue. I fixed it. Now if you follow all the steps described in the problem, an alert will appear with a warning. And also the marked days will become as before editing.

Bugfix: editing current period

---

src/modals/InfoModal.tsx
src/pages/TabDetails.tsx
src/pages/TabHome.tsx
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts
src/utils/translations/ru.ts

Closed #140 
I fixed the display of history with one cycle. Now, if only one cycle is marked, the application will look like this
Home tab if period today or delay: 
in Russian:
I made the "possible today" text size a little smaller. This will only happen if the `cycles.length === 1`.
Details tab:
Info Modal:

Calculations of the first cycle in history

---

src/pages/TabHome.tsx
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts

Closed #129 
Now the calendar marks the 6 nearest future cycles. Previously there was only 1.
I changed the `isForecastPeriodDays` function to `getForecastPeriodDays` function. Now the function is called once and returns an array of future dates.  Also I added a new test.

More future periods marked

---

src/App.css
src/data/Storage.ts
src/pages/TabHome.tsx
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts
src/theme/variables.css

Closed #169 
I added a display of ovulation. It looks like this:
If today is the ovulatory phase, it will look like this
Ovulation is also displayed for future cycles
I decided not to display ovulation if there is only one cycle in the array. I also decided to display only one future period for this case.
I added a test and fixed the tests in the `Storage.ts`. In them, the length of the first cycle was not equal to 0. 
The function for calculating ovulation days `getOvulationDays` now has a lot of ordinary numbers. I know they are not understandable. I'll make the calculations clearer in another task when we change the array in storage.

Add ovulation display

---

src/modals/WelcomeModal.tsx
src/pages/TabHome.tsx

Closed #153 
Now the maximum value is equals to current month
The minimum value is calculated based on the following logic. We getting first date of the first period and if this date is further than 6 months from today then this date will be min limitation, if this date is nearest than 6 months then 6 months from today will be the minimum for the `IonDateTime`

Add min and max limitations for `IonDateTime`

---

src/App.css

I didn't find related task in the `Issues` list
Previously when you click on today, border is disappeared
The similar problem was for ovulation days
I disabled possibility to handle events on the days when you in the calendar's view mode. With this restriction you can click on any day and a click event will be ignored, but you still able to move between months

Disabled possibility to select any date on the calendar's view mode

---

src/App.css
src/modals/WelcomeModal.tsx

Closes #152
Closes #154
We have 2 problems related to month/year selector. The same behavior reproduces with a default ion datetime and may be checked here https://ionicframework.com/docs/api/datetime
I tried to use all available props, css and callbacks to get rid of these bugs, but unsuccessfully.
After this I tried to think about user behavior and decided to disable month/year selection, because user has all necessary information about the previous periods in the `Details` tab. If the user needs to see specific month their should scroll back month by month. It takes longer, but does not conflict with the basic behavior of our users in my opinion
The only problem that remains is this arrow icon, I tried different css selectors, but I couldn’t get to this element and make it invisible

Disabled month/year selection

---

src/pages/TabHome.tsx
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts
src/utils/translations/ru.ts

Closed #166
Closed #171
In this PR I added possibility to save empty array of cycles. Also I removed isMarkedFutureDays because now we using ion-datetime built-in limitation instead of custom checks
Also I added the new test https://github.com/IraSoro/peri/issues/195

Added the last period force remove if user unmarked the first day of the last period

---

src/pages/TabHome.tsx

Closed #202 
I deleted the alert and added the disable property. Now the user will not be able to click on the `Mark button` if today is their period.

Added disable `Mark button`

---

src/App.tsx
src/data/Storage.ts
src/pages/TabDetails.tsx

Closed #172 
I changed the maximum number of cycle storage: it was 6, now 7. I did this so that there would be no error when a cycle was accidentally marked. (If there were 6 cycles, the user accidentally marked a new cycle, the last cycle is deleted because the maximum is 6. Then he cancels this last cycle. Now 5 cycles are stored)

Number of cycles stored

---

src/App.css
src/modals/Menu.tsx

Closed #216 
I fixed style for `IonSelect` component in case of dark theme
This is how it looks like:
I'm not sure about this styling, maybe it's could be better to use the same color scheme which we use for buttons or other interactive elements, something like this:
```css
ion-popover.dark {
--background: var(--ion-color-dark-dark);
}
ion-popover.dark * {
color: #000000;
}
ion-popover.dark .item-radio-checked {
background-color: var(--ion-color-dark-dark);
}
```
@IraSoro what do you think about that?

Fixed dark theme's `IonSelect` style

---

.github/workflows/build_lint_test.yml

Now `peri` code is checked and tested separately in every branch. I added additional ci check to test `main` branch in general with all merged changes
Additionally, I removed `nodejs 18` from matrix because this version is in maintenance now and not in active developmentю More info here https://nodejs.org/en/about/previous-releases

Removed `nodejs 18` from matrix and added ci check on `main` push

---

src/pages/TabHome.tsx

Closed #231 
Previously, when the cycles were empty, the `Info button` simply didn`t display. Now I've added an empty space in this case. So that the calendar and the `Mark button` don't move when updating.

Made large the height of the empty `Info button`

---

src/pages/TabDetails.css
src/pages/TabDetails.tsx

Closed #173 
I changed the design of the Details tab.
This is the old one:
This is the new one:
Now there is a problem that the code is written a little unclear in defining the color for the theme. Right now we only have light and dark ones. I know that Ionic has the ability to specify colors for the dark and light version. I created a [task](https://github.com/IraSoro/peri/issues/245) for this.

New tab design Details

---

src/modals/InfoModal.css
src/modals/InfoModal.tsx

Closed #252 
I corrected the design of the Info Modal a little. I didn't like the dots before the elements. It looked like a document.
This is a old design:
This is the new one:
I also moved some styles to the .css file because they were often duplicated.

Edit Info Modal design

---

src/App.css
src/modals/Menu.tsx

Closed #236 
I couldn't fix it, but I fixed another line at the bottom of the menu
This line:
I hope you can find a way to fix this

Removed the line under the app version

---

src/App.tsx
src/data/Storage.ts
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts

Closed #258 
I found the reason why the shift is happening. We have a maximum number of cycles in the storage. So if we already have the maximum number of cycles stored, then when adding a new one, one is deleted. If we return everything after this, then one of the cycles has already been deleted, so new average values ​​are recalculated. And since the average values ​​have changed, the forecast has changed.
I solved this problem like this.
1. I increased the maximum number of stored cycles to 8.
2. Now the average is calculated only from those cycles that are displayed in the application (6 of them). Therefore, 2 more will be spare, we do not take them into account in the calculations, but they are stored for these cases as in these bug.
I also found another bug. My `peri.json` file has …

Fix incorrect day shift after cycle edit

---

src/App.tsx
src/modals/Menu.tsx

Closed #270 
I fixed this problem.
But it will work only if: you already have a dark theme, you import a config with a dark theme, the alert is displayed with a dark theme. But if you import a config with a light theme, the alert will be displayed with a dark theme this time.
The dark alert looks like this:
I also removed the word `beta` from the dark theme selection.
And changed icon for theme select. The new icon looks like this

Fix import config alert

---

src/data/AppVersion.ts
src/modals/Menu.tsx
src/tests/AppVersion.test.ts
src/utils/translations/es.ts
src/utils/translations/ru.ts

Closed #271 
The link looks like this:
I made the window open on click. And added translation for the text.

Link to GitHub

---

CONTRIBUTING.md
src/utils/datetime.ts
src/utils/translation.ts
src/utils/translations/fi.ts

Happy Hacktoberfest! 🎃 
I added the Finnish translation (addressing issue #279) in translations/fi.ts and updated datetime.ts and translation.ts files as instructed. Ran formatter and linter as instructed, too.
I made a small addition to the Contributing instructions because I noticed myself almost overlooking the detail. I hope you find it useful!

Added Finnish translation and improved (slightly) Contributing instructions

---

src/App.tsx

Closes #322 
I set `href="#"` placeholder in the `IonTabButton` element to explicitly tell `react-router` that this tab should't redirect to any tab within the SPA

Fixed tab with id warning

---

LICENSE.txt
LOGO_LICENSE.txt
public/assets/icon/LICENSE.txt

Closes #340
I added modified MIT license described in the `LICENSE.txt`. This license is inspired by X11 MIT (more info here https://en.wikipedia.org/wiki/MIT_License). I added additional information about peri name and logo limitations. Also I added `LICENSE.txt` and `LOGO_LICENSE.txt` (duplicate) to show that peri logo is copyrighted

Added license files for project and logo

---

package-lock.json
package.json
src/data/Config.ts
src/data/Storage.ts
src/main.tsx
src/tests/Config.test.ts
src/tests/Storage.test.ts

Closes #255 
In this PR I changed `@ionic/storage` to `@ionic/preferences`. Looks like this should fix the problem with package upgrades
@IraSoro, could you check the following tests? (I can't build signed application in my docker image, so it's impossible to re-install application to check expected behavior)
Test migration from `@ionic/storage` to `@ionic/preferences`:
- Build current release version and install it
- Mark some cycles, change theme and language
- Build version with migration (current PR)
Expected: There shouldn't be any problems with migration and configuration should be applied without any error
Test migration from v5 to v6:
- Build version with migration (current PR)
- Mark some cycles, change theme and language
- Upgrade packages which you downgraded in this commit …

Migrate from storage to preferences

---

src/data/Storage.ts
src/modals/WelcomeModal.tsx
src/pages/TabDetails.tsx
src/pages/TabHome.tsx

Closed #339 
The problem on iOS was not related to the font. It was because Ionic use iOS mode for iOS. By default, the components were in Android mode. So I explicitly set the Android mode for the components.

Fixed style for ios

---

src/modals/InfoModal.css
src/modals/InfoModal.tsx

Closed #390 
After the update of last caoacitor version, a bug like this appeared in the Menu https://github.com/ionic-team/capacitor/pull/7871. I fixed it: added [env(safe-area-inset-top)](https://developer.mozilla.org/en-US/docs/Web/CSS/env) padding

Fix top position on the Info Modal
