IraSoro/peri

src/App.tsx

Added route for GitHub-Pages

---

src/pages/TabHome.tsx
src/pages/WelcomeModal.css
src/pages/WelcomeModal.tsx

Changed WelcomeModal ui.
Added "Config" and "Cancel" buttons.
Changed alerts style.

Changing WelcomeModal style

---

src/pages/TabDetails.tsx

Closed #50 
Example of the new view

Changed the view of information about the current cycle

---

src/modals/MarkModal.tsx

Error closing Mark modal

---

src/data/Storage.ts
src/pages/TabHome.tsx

Closed #38 
Changed calculations as described in the issue.
I also changed the data of the cycles, as these are outdated.

Editing pregnant change

---

src/pages/TabHome.tsx

Changed "Period to" and "Delay" for 1 day

---

src/data/Storage.ts

Closed #90 
New templates have been added. With them, you can view more options: different phases, days of ovulation and menstruation. And also in these functions there is an argument - a number, which means how many cycles to generate.

Rewrite test templates

---

src/modals/WelcomeModal.css
src/modals/WelcomeModal.tsx
src/translations/ru.tsx

Closed #102
I changed the ui. Now it looks like this
I also changed adding the item to the store. This is now done with the old function - ```getNewCyclesHistory``` from ```CalculationLogic```.

Edit welcome modal UI

---

README.md

Add `How to build` instruction in `README.md`

---

src/pages/TabDetails.tsx
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts
src/translations/en.tsx
src/translations/ru.tsx

Changed the message about information for current periods

---

src/modals/WelcomeModal.tsx

Added a restriction to mark a days after current one in the welcome modal

---

src/pages/TabHome.tsx

Changed font size in `TabHome` to `35px`

---

src/data/Storage.ts
src/languages/ru.tsx
src/pages/TabDetails.tsx

Closed #122 
I added a random function to generate different cycle lengths and period lengths.
I also fixed a bug with displaying the cycle history (the error was in ```Details.tsx```).
Also fixed a bug with translation.

Add random function

---

package-lock.json
package.json
src/data/AppVersion.ts
src/state/CalculationLogics.ts

Error in displaying active dates on the home calendar.
And I updated version (v2.3.2).

Hotfix: fixed active dates in the home calendar

---

src/languages/ru.tsx

Bug: No translation in the Menu

---

README.md
src/data/AppVersion.ts
src/tests/AppVersion.test.ts

Closes #130
Added the new checks and tests

Disable app update on Android Web

---

info/TEST_PLAN.md

Closes #133
I added the base of the test plan
To start a test plan you should create a new issue and copy list of tests in it
After this you should repeat steps described in a test and mark it as completed in the end

Added base of the test plan

---

README.md

Added link to calculations in README

---

README.md

Added `.apk` link in the `README.md` file

---

src/App.tsx

Closed #205 
I changed the paths from `/home` to `/peri/` and from `/details` to `/peri-details/`.

Changed a route path

---

src/App.css

Closed #201 
Closed #203
I changed style in the `Welcome modal` and changed current day style in `Edit Calendar`. Now the calendars look like this:

Changed calendars style

---

src/App.css
src/modals/WelcomeModal.tsx

Closed #184 
New color of buttons:

Change the color of buttons in the alert

---

src/App.tsx
src/index.tsx

Fixed blinking on startup with dark theme

---

src/App.css
src/pages/TabHome.tsx

Changed dark theme's circle color for today

---

src/App.css
src/pages/TabHome.tsx
src/utils/translations/ru.ts

Closed #233 
I added an alert. It looks like this:
I created a modal component (not an alert) because I want to add a link like in the screenshot. In the alert I can't do this.
I also created a new branch because I want to deploy every release with it. I won't merge it.

Added an alert to the demo

---

src/pages/TabHome.tsx
src/state/CalculationLogics.ts
src/tests/CalculationLogic.test.ts

Closed #221 
I rewrote several calculation functions. The logic of most of the calculations remained the same, I just rewrote it more beautifully. And also added comments.
All functions have passed the tests, but I still want you to check everything as carefully as possible.

Rewrite some calculation functions

---

src/modals/Menu.tsx

Added theme and language setting when importing configuration

---

src/pages/TabHome.tsx

Closed #247 
I slightly changed the design of the Info button to make it a little more visible and smoother.
The old version:

Fixed `InfoButton` design

---

src/utils/datetime.ts
src/utils/translation.ts
src/utils/translations/hg.ts

Hacktoberfest : Added Hinglish 

---

src/utils/datetime.ts
src/utils/translation.ts
src/utils/translations/id.ts

This PR addresses #279.
I added support for Bahasa Indonesia, hoping this helps more Indonesian speakers use Peri!

Add bahasa indonesia translation

---

public/manifest.json

Fixed the display of the icon on the phone screen when "adding to the main screen"

Returned icon parameters

---

src/data/Storage.ts

Hotfix #345 . Fixed migration theme.

Hotfix - theme migration

---

src/pages/TabHome.tsx

Closed #265 
Added a check so that if the number of cycles <= 1, then don't show the info button.

Remove Info button if there is only one cycle

---

README.md

Closed #366 
I created a [new repository](https://github.com/IraSoro/peri-storage) where screenshots are stored.
And updated the `README.md`.

New repository for storing screenshots

---

README.md

I added thanks section to `README.md`

Added thanks section to `README`

---

CONTRIBUTING.md
src/utils/translations/source.ts

Closed #361 
I created a file `./src/utils/translations/source.ts`. It describes the phrases for translation and explanations for them.
And also edited the `CONTRIBUTING.md` file.

Created a file for example translation

---

PRIVACY_POLICY.txt

Closes #277
I don't know what to add here

Added privacy policy

---

index.html
src/App.tsx
src/main.tsx
src/modals/Menu.tsx

Closes #335 
I don't like that there is code duplication, but for now it's ok to make this until we'll test behavior on various devices
Result
Android
iOS

335 change status bar on pwa according to current theme

---

CONTRIBUTING.md
src/modals/Menu.tsx
src/utils/notifications.ts
src/utils/translations/example.ts
src/utils/translations/ru.ts

Closes #365 
Renamed `Notification` to `Notifications`
Renamed `source.ts` to `example.ts` and changed `CONTRIBUTING.md` accordingly
Wrapped notifications with i18n translation function
Added Russian translation for notifications and

Added translation for notifications

---

src/App.tsx
src/data/Storage.ts
src/modals/InfoModal.tsx
src/modals/Menu.tsx
src/pages/TabDetails.tsx
src/pages/TabHome.tsx
src/state/CalculationLogics.ts
src/state/Context.tsx
src/tests/CalculationLogic.test.ts
src/tests/Config.test.ts
src/utils/notifications.ts
src/utils/translations/example.ts
src/utils/translations/ru.ts

Closed #341 
I added the ability to choose how many cycles to store for the user. Previously there were only 6 (actually 8, 2 are spare). Now there is a choice of 6, 12, 24. For this, I added a new variable to the storage. I also had to rewrite the logic a little. I didn't like it. I'll be glad if you write ideas on how to do it better.

Store more cycles

---

src/utils/translations/es.ts

Closed #386 
Closed #387 
I changed the phrase "Welcome to Peri" in the Spanish translation. And added a new translation for the phrase "Stored cycles count"

Change some phases in the Spanish translation

---

src/utils/datetime.ts
src/utils/translation.ts
src/utils/translations/pt.ts

I added the translation for portuguese following the guidelines in the CONTRIBUTING.md

Add Portuguese translations

---

src/utils/translation.ts
src/utils/translations/ar.ts

This pull request adds support for the Arabic language to the application by introducing translations and updating the language configuration. The main changes include importing the Arabic translation file, adding Arabic to the list of supported languages, and updating the language initialization logic to recognize and load Arabic translations.
**Arabic language support:**
* Added a new Arabic translation file `ar.ts` with comprehensive translations for all major UI elements and messages.
* Imported the new `ar` translation module into the main translation utility (`src/utils/translation.ts`).
* Added Arabic ("ar", "العربية") to the `supportedLanguages` map, making it selectable in the language menu.
* Registered the Arabic translations in the language initialization function, ensuring …

feat : Add Arabic translations and support to the translation module

---

src/App.css
src/modals/Menu.tsx

Add custom styles for IonAlert buttons with a soft light purple background and purple text by default. On hover, buttons now switch to #4d3b9e background with white text for better emphasis and accessibility.
Issue solving #401

Style IonAlert buttons with purple hover effect

---

src/utils/translations/ar.ts

- Use natural Arabic phrases.
- Fixed gender agreement.
- Updated "day" format to use Arabic ordinals for more natural cycle day references.
- Smoother/lighter tone of voice.

Update Arabic translations for various terms
